---
- name: Patch Fedora VM via openshift_virtualization
  hosts: vmexamples-user1-fedora02
  gather_facts: yes
  collections:
    - redhat.openshift_virtualization


  vars:
    namespace: ""
    vm_name: ""

  tasks:
    - name: Ensure kubernetes Python library is installed
      pip:
        name: kubernetes
        executable: pip3
        
    - name: Get Fedora VM object
      redhat.openshift_virtualization.kubevirt_vm_info:
        namespace: "{{ namespace }}"
        name: "{{ vm_name }}"
      register: vm_info

    - name: Debug VM status
      debug:
        var: vm_info.resources[0].status


