---
- name: Patch Fedora VM via openshift_virtualization
  hosts: all
  gather_facts: true
  ignore_unreachable: yes

  tasks:
    - name: Debug dynamic variables
      debug:
        msg: "Namespace: {{ vm_namespace }}, VM Name: {{ inventory_hostname }}"

    - name: Patch the Fedora VM with DNF only for security pataches
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_only: yes
        security: yes
      register: dnf_result

    - name: Reboot the VM if packages were updated
      when: dnf_result.changed
      block:
        - name: Restart the VM gracefully
          ansible.builtin.reboot:
            reboot_timeout: 600
