---
- name: Patch Fedora VM via KubeVirt API
  hosts: localhost
  gather_facts: false
  collections:
    - redhat.openshift_virtualization

  vars:
    vm_namespace: vmexamples-user1
    vm_name: fedora02-vmexamples-user1
    container_name: fedora02   # default container name in VM pod

  tasks:
    - name: Get VM info
      kubevirt_vm_info:
        name: "{{ vm_name }}"
        namespace: "{{ vm_namespace }}"
      register: vm_info

    - name: Debug VM status
      debug:
        var: vm_info.resources[0].status.printableStatus

    - name: Run DNF update inside the VM
      kubevirt_vm_exec:
        name: "{{ vm_name }}"
        namespace: "{{ vm_namespace }}"
        command: ["sudo", "dnf", "-y", "update"]
      register: update_result

    - name: Show update output
      debug:
        var: update_result.stdout

    - name: Reboot VM
     kubevirt_vm_exec:
        name: "{{ vm_name }}"
        namespace: "{{ vm_namespace }}"
        command: ["sudo", "systemctl", "reboot"]
