---
- name: Patch Fedora VM via openshift_virtualization
  hosts: vmexamples-user1-fedora02
  gather_facts: yes
  collections:
    - redhat.openshift_virtualization

  vars:
    namespace: ""
    vm_name: ""

  tasks:
        
    - name: Get Fedora VM object
      redhat.openshift_virtualization.kubevirt_vm_info:
        host: "{{ k8s_api_host }}"
        api_key: "{{ k8s_bearer_token }}"
        namespace: "{{ namespace }}"
        name: "{{ vm_name }}"
      register: vm_info

    - name: Debug VM status
      debug:
        var: vm_info.resources[0].status.printableStatus


