---
- name: Patch Fedora VM via OpenShift API
  hosts: all
  gather_facts: no


  vars:
    namespace: ""
    vm_name: ""

  tasks:

    - name: Get Fedora VM object
      redhat.openshift_virtualization.kubevirt_vm_info:
        namespace: "{{ namespace }}"
        name: "{{ vm_name }}"
      register: vm_info

    - name: Debug VM status
      debug:
        var: vm_info.resources[0].status


