---
- name: Patch Fedora VM via openshift_virtualization
  hosts: all
  gather_facts: false

  pre_tasks:
    - name: Check for SSH connectivity
      ansible.builtin.wait_for_connection:
        timeout: 10  # Wait a maximum of 10 seconds for a connection
      ignore_errors: yes  # IMPORTANT: Suppresses errors if the host is unreachable
      register: ssh_check_result

  tasks:
    - name: Gather facts for reachable hosts
      ansible.builtin.setup:
      # This 'when' condition is the gatekeeper for all subsequent tasks
      when: ssh_check_result is succeeded

    - name: Apply security patches using DNF
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_only: yes
        security: yes
      register: dnf_result
      when: ssh_check_result is succeeded

    - name: Reboot the VM if a patch was applied
      ansible.builtin.reboot:
        reboot_timeout: 600
      when:
        - ssh_check_result is succeeded
        - dnf_result.changed
